# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
   GOOGLE_CLIENT_ID: 610612216570-ti8l8mocpfjkuhsfl7m788fa0p55vqkf.apps.googleusercontent.com
   GOOGLE_CLIENT_SECRET: rZ1RGSqn4EZsWjRFW4gU7SVc
   INSTAGRAM_CLIENT_ID: 7f648a58235f44eda1aabf198cda6590
   INSTAGRAM_CLIENT_SECRET: d56b68baceac454a9dbb4bd1e3065097
production:
   GOOGLE_CLIENT_ID: 610612216570-ti8l8mocpfjkuhsfl7m788fa0p55vqkf.apps.googleusercontent.com
   GOOGLE_CLIENT_SECRET: rZ1RGSqn4EZsWjRFW4gU7SVc
   INSTAGRAM_CLIENT_ID: 7f648a58235f44eda1aabf198cda6590
   INSTAGRAM_CLIENT_SECRET: d56b68baceac454a9dbb4bd1e3065097